### ISSUE TITLE
dev: make the retry service interval time configurable by environment variable

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1035]
**Describe the enhancement request**

we currently sleep 30s between retries, we should be able to change this numberr

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] create an env variable for retry interval
- [ ] we can decide that the default value is 10 seconds, can be 30s
- [ ] set it on karnot to become 2s on testnet
- [ ] think of a way to make it configurable at runtime? in high congestion times, retry time should be long. otherwise could be 1s
- [ ] for katana runs, set the interval to be 0.5s -> change the docker compose file that uses katana 
```
