### ISSUE TITLE
bug: specific Reno forge script not working

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1042]
# Bug Report

### Warning ⚠️ - needs more scoping 

**Kakarot RPC version:**

v0.7.2

**Current behavior:**

Reno is trying  to run a specific script to deploy his smart wallet on Kakarot Sepolia. He has managed to deploy it to Sepolia L1.
He gave us the script he's running.

```[tasklist]
### Tasks
- [ ] run make local-rpc-up
- [ ] run the reno script on localhost
- [ ] check logs to understand
``` 

For archive, text Elias.
After opening the archive:
from Reno:
```
> forge test pour vérifier que c'est ok 
>./deploy.sh pour déployer, j'ai laissé la clé de test en dur (safu)
Normalement le compte est appro sur sepolia main et OP et KKR pour comparer les comportements
```

Bug:
![telegram-cloud-photo-size-4-5875247431518633759-y](https://github.com/kkrt-labs/kakarot-rpc/assets/66871571/a4be750b-d338-4c71-be51-3b9eee6d58a6)

**Expected behavior:**

**Comment by greged93** [comment]
Adding the zip of the script used
[KKR.zip](https://github.com/kkrt-labs/kakarot-rpc/files/15185871/KKR.zip)

**Comment by Eikix** [comment]
> Adding the zip of the script used [KKR.zip](https://github.com/kkrt-labs/kakarot-rpc/files/15185871/KKR.zip)

Initially didn't add because it has a private key;p

**Comment by greged93** [comment]
raised https://github.com/foundry-rs/foundry/issues/7833

**Comment by tcoratger** [comment]
@greged93 Closed by https://github.com/foundry-rs/foundry/pull/7838 no?
