### ISSUE TITLE
epic dev: add `Providers` for each server

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1277]
**Describe the enhancement request**

Currently, we have a `EthProvider` which is an abstraction over the Ethereum RPC spec. At the Eth RPC layer, we thus makes calls to this abstraction.

On order servers (trace, alchemy, debug, pool), we have the actual implementation at the RPC layer. Ideally, we would like to have a similar abstraction as the Eth Provider, which would also allow us to update the testing. The following RPC servers need to be updated:

Time: 6 hours

**Tasks:**

```[tasklist]
### Tasks
- [x] Alchemy provider abstraction
- [x] Debug provider abstraction
- [x] Pool provider abstraction
```
