### ISSUE TITLE
test: update testing for `Trace`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1278]
**Describe the enhancement request**

Currently the testing for the tracing starts up a whole RPC server. This causes some overhead in the testing and is actually not necessary. We could just initiate a `TracerBuilder` with a `EthProvider` instance and just work with this instance for all the tests.

Move the following tests into a `tracer.rs` file in the `tests` folder, remove the use of `start_kakarot_rpc_server` and use the `TracerBuilder` instead.

Time: 4 hours

```[tasklist]
### Tasks
- [x] test_trace_block
- [x] trace_block_by_number
- [x] test_debug_trace_block_by_number
- [x] test_debug_trace_transaction
```
