### ISSUE TITLE
dev: add migration procedure for the MongoDB [2]

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1293]
**Describe the enhancement request**

Indexes have been added to the Mongo but we should have some migration procedure from Karnot in case we ever want to update these or change the Mongo models. This needs to be discussed with Karnot.

```[tasklist]
### Tasks
- [ ] create a `migrations` folder at the root of the project
- [ ] add a init file like in https://github.com/madara-alliance/madara-orchestrator/blob/main/migrations/00000000000000-init.js
- [ ] put inside the indexes (see below)
```

```js
db.headers.getIndexes()
[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  { v: 2, key: { 'header.hash': 1 }, name: 'header.hash_1' },
  { v: 2, key: { 'header.number': 1 }, name: 'header.number_1' },
  { v: 2, key: { '_cursor.from': 1 }, name: '_cursor.from_1' },
  { v: 2, key: { '_cursor.to': 1 }, name: '_cursor.to_1' }
]

db.receipts.getIndexes()
[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  {
    v: 2,
    key: { 'receipt.blockHash': 1 },
    name: 'receipt.blockHash_1'
  },
  {
    v: 2,
    key: { 'receipt.blockNumber': 1 },
    name: 'receipt.blockNumber_1'
  },
  {
    v: 2,
    key: { 'receipt.transactionHash': 1 },
    name: 'receipt.transactionHash_1'
  },
  { v: 2, key: { '_cursor.from': 1 }, name: '_cursor.from_1' },
  { v: 2, key: { '_cursor.to': 1 }, name: '_cursor.to_1' }
]

db.transactions.getIndexes()

[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  { v: 2, key: { 'tx.blockHash': 1 }, name: 'tx.blockHash_1' },
  { v: 2, key: { 'tx.blockNumber': 1 }, name: 'tx.blockNumber_1' },
  { v: 2, key: { '_cursor.from': 1 }, name: '_cursor.from_1' },
  { v: 2, key: { 'tx.hash': 1 }, name: 'tx.hash_1' },
  { v: 2, key: { '_cursor.to': 1 }, name: '_cursor.to_1' }
]

db.logs.getIndexes()
[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  { v: 2, key: { '_cursor.from': 1 }, name: '_cursor.from_1' },
  { v: 2, key: { '_cursor.to': 1 }, name: '_cursor.to_1' }
]
```

**Comment by greged93** [comment]
@anukkrit149 is this still needed?

**Comment by Eikix** [comment]
This issue needs scoping cc'ing @ClementWalter, as it has been mentioned now twice in Karnot weeklies, we need a MongoDB migration script that's ran every time we redeploy the mongoDB
