### ISSUE TITLE
epic: refactor the `EthProvider` trait

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1326]
# Feature Request

**Describe the Feature Request**

In order to prepare for the upgrade to the `execute_from_outside`, a refactor of the `EthProvider` trait is needed in order to bring more modularity into the codebase. The current plan is to split the `EthProvider` trait into:
- State Provider: gives access to address state (bytecode, nonce, balance,...). See [Reth](https://github.com/paradigmxyz/reth/blob/27d21b037476a8ae2a490190ef0fdfe506e34ef8/crates/storage/storage-api/src/state.rs#L15).
- Block Provider: gives access to block related information. See [Reth](https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/consensus/debug-client/src/client.rs#L18). Will use the below traits in order to provide all this information.
- Receipt Provider: gives access to receipts. See [Reth](https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/storage/storage-api/src/receipts.rs#L10).
- Transaction Provider: gives access to receipts. See [Reth](https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/storage/storage-api/src/transactions.rs#L24).
- Header Provider: gives access to receipts. See [Reth](https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/storage/storage-api/src/header.rs#L7).

![image](https://github.com/user-attachments/assets/debef38b-b019-4c52-8017-d8c2d5fa8c9d)

All these various providers will be accessible via the [`EthApi` structure](https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/rpc/rpc/src/eth/core.rs#L174), which will contain the provider and the mempool. 

The mempool should also be able to access the state of a particular account, and as such should hold a reference to a `StateProvider`.

```[tasklist]
### Tasks
- [x] Define the `EthApi` structure.
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/1327
- [x] Implement each `Provider`.
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/1319
- [ ] Replace the `EthDataProvider` with the `EthApi` structure.
```
