### ISSUE TITLE
dev: update repo to 0.7.1

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1426]
**Describe the enhancement request**

We have just released `v0.7.1`. There are a couple of values that need to be updated since this release:

- Cargo.toml: bump to 0.7.1
- Dockers: bump all mentions of the `kakarot-rpc` service to 0.7.1 and check that the env is correct (should now include `RELAYERS_ADDRESSES` and `RELAYER_PRIVATE_KEY`).

```[tasklist]
### Tasks
- [ ] Bump Cargo.toml to `0.7.1
- [ ] Verify that all the dockers (dockerfile and compose) are pointing to the correct versions for dna, sink-mongo and kakarot-rpc
- [ ] Check that the env is correct (should now include RELAYERS_ADDRESSES and RELAYER_PRIVATE_KEY).
```
