### ISSUE TITLE
epic: Relayer Transaction Monitoring Service

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1456]
**Describe the enhancement request**

Kakarot just landed on Starknet Sepolia, making the network EVM compatible. EVM Transactions are relayed by a permissionless fleet of relayers operated currently by Kakarot Labs.

There is currently no visibility / observability framework to compute statistics on the transactions that are being emitted by relayers. We need a service that's able to:
- Link an EVM transaction hash with its corresponding Starknet Transaction Hash for ease of debug
- Alert Kakarot Labs if relayer transactions are being rejected 
- Receive/Index receipts of relayers transactions and alert if transactions are being reverted -> Why? Because transactions MUST not be Starknet reverted (if they revert in EVM world, they are still successful but carry a failure flag)

**Describe Preferred Solution**

- A Relayer Transaction Monitoring Service - needs further scoping by @greged93 and @tcoratger 

```[tasklist]
### Tasks
- [ ] Link Ethereum and Starknet transactions hashes so that Kakarot Labs team member can easily pick up an Eth transaction hash from a user and gather information on the transaction
- [ ] Be able to alert Kakarot Labs if OZ relayer service faces "transaction rejected" on Starknet, and give us the reason
- [ ] Be able to draw statistics on % of Successful relayer transactions on testnet (note that for relayers, starknet reverted transactions are not reimbursed)
- [ ] Be able to alert if transactions are being Starknet reverted
```

**Comment by Eikix** [comment]
Needs scoping with respect to technical strat cc'ing @ClementWalter
