### ISSUE TITLE
feat: index cairovm errors [6]

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-rpc#1458]
We are throwing cairovm errors in a few cases that should be indexed if possible:

- calls to starknet contract will be able to fail. there is no specific error message to catch, it can fail with anything
- we trigger a hard revert of the whole transaction if an EVM context fails AND a starknet call was made in the current transaction. the message is: `EVM tx reverted, reverting SN tx because of previous calls to cairo precompiles`

```[tasklist]
### Tasks
- [ ] Use the `includeReverted` filter in ApiBara on the Transactions
- [ ] Check if the revert message includes `EVM tx reverted, reverting SN tx because of previous calls to cairo precompiles`: If it does add extra context to the stored transaction (i.e.`isCairoPrecompileCallRevert` or something). if not, just index the transaction with `unknownCairoCallRevert` as context.
- [ ] Add unit tests in the indexer
- [ ] Add unit tests in the RPC
- [ ] Optional (spend max 2 hours): [Filter on calldata](https://arc.net/l/quote/keitwezj) in order to include transactions that targeted the Kakarot address
```

Duration: 6 hours

**Comment by Eikix** [comment]
We might have to start having a typology of possible errors, such as "KKT86" etc. like in other protocols + documentation for all errors

Resulting UX would be that users seeing a specific error in `cast receipt tx_hash` or the explorer UI:
<img width="559" alt="image" src="https://github.com/user-attachments/assets/a907c0c4-0ffa-4e96-b99b-3535c218aef2"> will be able to debug their error code!

**Comment by greged93** [comment]
@enitrat can you provide a transaction that fails with the `EVM tx reverted, reverting SN tx because of previous calls to cairo precompiles` message and another that fails without a specific message?
