### ISSUE TITLE
Prune the mempool [0.5]

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1478]
In the `maintain_transaction_pool` service running, we need to add a pruning of the transactions that have been sitting in the mempool for more than X minutes.
```[tasklist]
### Tasks
- [ ] Check Reth implementation
- [ ] Write unit test to confirm the pruning
- [ ] Transpose to the RPC
```

Duration: 0.5 hours
