### ISSUE TITLE
EPIC: make the kakarot-rpc codebase healthier before testnet

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#148]
Audit Kakarot-rpc codebase as we're shifting focus from Madara to Kakarot-rpc to prepare for public testnet.

As discussed in chat, we can assess:
- is business logic where it should be
- how did we separate the crates and rust workspace logic
- how did we implement trans-format logic? (eth blocks to starknet blocks) etc. -> newtype? wrappers?
- are traits well defined? is it sustainable?
- are we still importing reth types? where why? or still copy pasting a trait

Meeting: https://hackmd.io/6sAIUFV3Tf2t6P6Sn_MeiA

```[tasklist]
### Tasks
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/149
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/150
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/151
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/152
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/153
- [x] https://github.com/kkrt-labs/kakarot-rpc/issues/154
```
