### ISSUE TITLE
feat: create a type wrapper around starknet-rs block (newtype)

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#149]
Current type format mappings:

![image](https://github.com/kkrt-labs/kakarot-rpc/assets/66871571/855fbcf4-6413-4dcd-bb8c-29f707dcc9f3)

```[tasklist]
### Tasks
- [x] rename `types.rs` into `models.rs`
- [x] create a wrapper struct around `MaybePendingBlockWithTxHashes`
- [x] create a wrapper struct around `MaybePendingBlockWithTxs`
- [x] create a trait called ConvertibleEthBlock
- [x] create a function called `into_eth_block` in this trait, currently, it'll take on argument, a dyn KakarotClient
```
