### ISSUE TITLE
feat: create a type wrapper around starknet-rs transaction

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#150]
depends on #149 (for renaming the file types.rs into models.rs)

![image](https://github.com/kkrt-labs/kakarot-rpc/assets/66871571/143464b4-aa8a-4b33-b60c-a765834de6cf)

```[tasklist]
### Tasks
- [ ] Create a type wrapper around `StarknetTransaction` from starknet-rs inside models.rs
- [ ] Create a trait called ConvertibleEthTx
- [ ] Create a function called into_eth_tx, currently, it can take an argument which impl. dyn KakarotClient
```
