### ISSUE TITLE
refactor: filter_starknet_starknet_tx_into_kakarot_tx using type wrapper impl.

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#152]
```[tasklist]
### Tasks
- [x] implement ConvertibleEthTx for wrapper StarknetTransaction
- [ ] create intermediary function for StarknetTransaction wrapper `is_kakarot_tx` that returns a boolean over whether a starknet tx is associated with kakarot (can extract logic from `filter_starknet_tx_into_kakarot_tx`)
- [x] implement `into_eth_tx` for ConvertibleEthTx trait by extracting logic from filter_starknet_tx_into_kakarot_tx
- [x] refactor code to use `into_eth_tx`
- [x] delete filter_starknet_tx_into_kakarot_tx
```
