### ISSUE TITLE
dev: using an ethereum transaction hash, retrieve the corresponding starknet transaction [3]

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1521]
**Describe the enhancement request**

IF I have a valid Ethereum transaction Hash
THEN I can request to RPC for corresponding Starknet transaction hash

**Describe Preferred Solution**

When a transaction is fired by a relayer, after send_raw_transaction route is successful, then store a mapping ethereum transaction to starknet transaction

```[tasklist]
### Tasks
- [ ] in `Relayers::relay_transaction`, add a database connector
- [ ] Before returning `Ok(res.transaction_hash)` insert the mapping into the `transaction_hashes` collection
- [ ] in `getTransactionByHash`, get the corresponding starknet hash from the requested eth hash
- [ ] in `getTransactionByHash`, use `other_fields` to return add the starknet transaction hash : ` starknet_transaction_hash: hash`
```
