### ISSUE TITLE
feat: replace python devnet by katana, remove python as dependency

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#158]
# Feature Request

**Describe the Feature Request**
feat: replace python devnet by katana, remove python as dependency

```[tasklist]
### Tasks
- [ ] Add Katana to the repo
- [ ] Integrate Katana in kakarot-rpc
- [ ] Remove python as dependency
``` 

Remaining questions:
- Do we use docker or directly rust binary?
- Do we need to alter kakarot-rpc Dockerfile?

**Comment by bajpai244** [comment]
@Eikix , since I have worked on the docker image, I guess I can take this.

On your questions here are my views and suggestions:
**- "Do we use docker or directly rust binary?"**

I guess it is better to use the docker container, otherwise, we would have to either add katana as a submodule, which will get built then, or use direct binaries, in that case again we would have to use some shell scripting to run the correct one.

This all has already been taken care of in the docker container, and since it has mult-arch built, it will run on native speed.

If someone wants to run the rust binary themselves, then they can do it themselves, as the RPC will simply connect with the local binary via the `.env` config.

If need be we can in the future add support for Rust binary as well.

**"Do we need to alter kakarot-rpc Dockerfile?"**

I don't think we need to change anything for that, as the RPC simply takes in `.env` config to decide where to connect. So, as far as I can see, there should be no need to change it.

**Comment by Eikix** [comment]
Alright sounds good to me;D
