### ISSUE TITLE
feat: create new type wrapper around `reth_primitives::BlockId` and implement to_starknet_block_id() for it

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#165]
# Feature Request

```[tasklist]
### Tasks
- [ ] create a wrapper around BlockId in core crate `models.rs`
- [ ] create trait in convertible.rs module, and only function is `to_starknet_block_id` 
- [ ] implement to_starknet_block_id by copy pasting logic from `ethers_block_number_to_starknet_block_id` in helpers.rs
- [ ] test the function
- [ ] delete ethers_block_number_to_starknet_block_id
```
