### ISSUE TITLE
dev: stop using safe_get_evm_address() 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#187]
```[tasklist]
### Tasks
- [x] replace `safe_get_evm_address()` by `get_evm_address()` in the codebase for starknet addresses that have an EVM address
- [x] replace `safe_get_evm_address()` by `starknet_address_to_evm_address()` in the codebase for starknet addresses that have an EVM address
- [ ] create a newtype pattern for Starknet Addresses `pub struct StarknetAddress(FieldElement)`
- [ ] implement From for reth's ethereum Address type
- [ ] refactor starknet_address_to_evm_address to be into()
- [ ] refactor get_evm_address to be a specific trait function for StarknetAddress, that gets passed the starknet client only to be used by well-defined Kakarot Starknte addresses that are able to be converted to evm addresses using get_evm_address() entrypoint
```
