### ISSUE TITLE
dev: add unit testing for models

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#208]
Add unit testing for type conversion in the `models` folder.
```[tasklist]
### Tasks
- [ ] Add unit testing for Felt252Wrapper
- [ ] Add unit testing for signature
- [ ] Add unit testing for calls
- [ ] Add unit testing for blocks
- [ ] Add unit testing for events
- [ ] Add unit testing for transactions
```
