### ISSUE TITLE
feat: prepare a demo for starknetcc

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#287]
# Feature Request

**Describe the Feature Request**

Let's prepare something cool for StarknetCC!

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] Have forge scripts work on Katana/Madara, and/or Goerli Testnet
- [ ] Have a working faucet to fund Starknet addresses and EOA smart wallets for new testnet users 
- [ ] Be able to deploy an EOA for a new Kakarot user
- [ ] Be able to get faucet funds with an EOA for a new kakarot user
- [ ] Start a dummy NFT app to showcase buying an NFT and "spending" money on Kakarot zkEVM
```

**Comment by Eikix** [comment]
What do you mean?

**Comment by Eikix** [comment]
> I can start investigating the forge script on Katana/Madara and Goerli.

What do you mean

**Comment by jobez** [comment]
hey guys, i am seeing success* deploying to madara with the following command 


`forge script scripts/PlainOpcodes.s.sol --broadcast --legacy --compute-units-per-second 4000 --fork-url http://0.0.0.0:3030 --slow `

only change is the one that elias incorporated in his provider pr around making sure transaction_index in TransactionRecept isnt None. 

some notes about the flags:

--slow makes sure that one transaction is only sent after the previous is confirmed/succeeded. 

--compute-units-per-second https://docs.alchemy.com/reference/compute-units
'This is used to guesstimate how long to retry again'
from the ethers docs: https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/rpc/transports/retry.rs#L110 

*where success means you cant deploy more than once, but i think that's complexity with forge script, will try doing deploys using forge create after i confirm being able to deploy on a freshly deployed madara two or three times

here's a manual session i did w/ forge and cast. wanted to demo the tooling while also begin collecting the error cases: https://gist.github.com/jobez/f1c3f655308d080757569f0c10fb4ba3

there are some issues showing up when we actually try to do calls/writes beyond just incing the counter, in both dojo and madara. experimenting with calls in PlainOpcodes, will work on recreating some of the vm errors w/ testsequencer

**Comment by Eikix** [comment]
Closing this as starknetcc went well! And we onboarded new testers
thanks to this tutorial https://kakarotlabs.notion.site/Run-Kakarot-Locally-using-Docker-33d3b0b12be641eea563b4fb8eb3d33e?pvs=4
