### ISSUE TITLE
dev: assess the quality of function signatures in `eth-rpc` crate with respect to Rust ownership: pass vars by reference or not

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#297]
# Feature Request

**Describe the Feature Request**

This is an investigation and exploratory issue to assess the quality of our function signatures. An argument can be passed to a function directly (consumes variable, or transfers ownership) or by reference (doesn't consume the variable).

Let's find out if we pass arguments correctly in our `new` functions for structs, but also when running servers, etc.
A good example was the `to_eth_log` function in models folder. When passing arguments by reference, we had lifetime issues, and consuming the arguments was the way to go! So it's def an open question.

Note that as much as possible, we should pass arguments by reference, as it saves us the occasional cloning. 

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] Go through implementations of structs in the core crate 
- [ ] Try to play around by replacing direct passing by references and see what happens
- [ ] Give feedback on what typology of cases warrants passing by reference, and what cases should require passing directly a variable in a function
- [ ] Feel free to check how other repos do it (pathfinder, reth, alloy, etc.)
``` 

Note that the same issue exists for `core` crate
