### ISSUE TITLE
epic: Benchmark TPS of native Eth transfer on Kakarot

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#322]
# Feature Request

The feature request is to implement TPS benchmarks for native Eth transfer on Kakarot, this can help us get some meaningful early figures about the system.

**Describe Preferred Solution**

We can use [Artilley](https://www.artillery.io/) to explore this.

```[tasklist]
### Tasks
- [x] Run benchmarks locally on Madara
- [x] Run benchmarks on testnet
- [x] Run benchmarks in CI
```

**Comment by Eikix** [comment]
Making this into a macro-task (aka epic) since it is quite a substantial issue

**Comment by bajpai244** [comment]
Breaking this tasks into two PR:
- Benchmarks on Madara
- Benchmarks on Testnet

I have created two issues for it as well, the epic can be completed done when PRs for both the below issues are merged:
- Issue for benchmarks on Madara
- Issue for benchmarks on Testnet

**Comment by Eikix** [comment]
Going to run our test quickly to see the result
