### ISSUE TITLE
epic: Implement official Ethereum conformance tests for Kakarot-Rpc -> RPC-Compat

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#342]
# Feature Request

We want to assess the soundness of our EVM.
There are a few official test suites to assert an EVM follows the specs.

@jobez started to track these in #130 

**Describe the Feature Request**

Super dream: We want to be able to run the RPC-Compat tests against Kakarot-Rpc from the CI.
Concrete result: Be able to actually just run the test suite. 

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/343
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/344
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/345
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/346
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/353
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/347
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/348
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/436
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/447
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/349
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/350
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/451
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/465
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/352
```
