### ISSUE TITLE
feat: translate the genesis state given by hive into a valid genesis state for Madara

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#345]
The genesis state for Madara contains 3 main fields: declared contract classes (mapping class hashes to class), deployed contracts (mapping starknet address to class hash) and storage (mapping a tuple of contract address and storage key to a value). The genesis of rpc tests contains EOA addresses that need to be funded with a certain amount and contracts that need to be deployed at a specific address, with a specific bytecode and sometimes some storage. The script written should thus be able to:
- Map EMV addresses to Starknet addresses given the Kakarot address.
- Modify genesis storage to fund EVM addresses.
- Deploy bytecode at a EVM contract address.
- Set the storage for a EVM contract address.

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/354
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/382
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/377
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/379
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/384
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/394
```

**Comment by Eikix** [comment]
Spec needed @greged93

**Comment by Eikix** [comment]
Unassigning @ftupas for now as he is currently focusing on test sequencer on eth-rpc crate in kakarot-rpc #365 
Always possible to reassign you when you come back to this task, 

Next sub-task in this issue:
- identify next step after util compute_starknet_address is done and add to the tasklist
- solve the resulting sub issue first

**Comment by ftupas** [comment]
Closing this as all subtasks are done
