### ISSUE TITLE
dev: create a make dump-katana script

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#414]
**Describe the enhancement request**

We want to be able not deploy the kakarot system (set of SC) every time we run an integration test on kakarot-rpc 

How? Using Katana dump state capability https://github.com/dojoengine/dojo/pull/674

```[tasklist]
### Tasks
- [ ] Create a Rust script that initializes a testsequencer, deploys a kakarot system, dumps it in a file that always has the same name, in the same folder (should be .gitignored) -> can be named `.katana/dump.<whatever the extension is>`
- [ ] create a make command that runs this rust script
- [ ] add this `make dump-katana` in the `make test` command -> for it to run right before `make test`, if `make test` doesnt exist, then create it 
``` 

**Describe Preferred Solution**
