### ISSUE TITLE
dev: refactor integration tests in kakarot-rpc to use make dump-katana from #414 rather than deploy kakarot system every time

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#415]
**Describe the enhancement request**

Problem: Integration tests are slow
Solution: we can use Katana dumps to load the set of SC for Kakarot faster in every test
In #414, we defined a way to dump some kakarot system to Katana dump file, we can now use this file to be loaded in all tests

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [x] Load Katana dumped state into the test sequencer for each integration tests
- [x] Delete the deploy_system that is in every integration tests
- [x] Make sure `make dump` is called before tests are loaded
- [ ] Explore whether rs-tests can load these fixtures rather than doing it at the make file level
```
