### ISSUE TITLE
feat: Make benchmarking CI faster

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#422]
# Feature Request

The current benchmark job on the CI takes a lot of time and sometimes fails because of the following reason:
- Madara binaries not working as of now
- Lack of faster runner

The following tasks should be explored and executed in this epic:
```[tasklist]
### Tasks
- [ ] Explore fixing Madara binaries with the Madara team
- [ ] Exploring either a self-hosted runner or a bigger runner for CI
- [ ] Move the benchmarking job back to run on every pull request when we get this job being executed faster
```
