### ISSUE TITLE
epic: improve CI time

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#456]
**Describe the enhancement request**
This epic task aims to accelerate the CI time.

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/457
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/458
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/444
```
