### ISSUE TITLE
feat: update Kakarot send_transaction API to follow the latest commit

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#487]
# Feature Request

**Describe the Feature Request**

https://github.com/kkrt-labs/kakarot/blob/47cdfdfff90b86cc191060e7d01945f3efeee0a3/src/kakarot/kakarot.cairo#L157

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] Check the changes needed to be able to update the Kakarot submodule
- [ ] Check the ETH_CALL signature changes
- [ ] Check the ETH_SEND_TRANSACTION signature changes, and check EOA implementation in cairo0 as it has some special behaviour
```
