### ISSUE TITLE
epic: create and implement the Debug API for Ethereum JSON RPC

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#519]
# Feature Request

**Describe the Feature Request**

Create the Debug Api and implement some of the endpoints for #130 

```[tasklist]
### Tasks
- [ ] Create the Eth JSON RPC Debug API 
- [ ] feat: debug_getRawTransaction endpoint
- [ ] feat: debug_getRawBlock endpoint
- [ ] feat: debug_getRawHeader endpoint
- [ ] feat: debug_getRawReceipts endpoint
``` 

**Describe Preferred Solution**

Draw inspiration from:
https://github.com/paradigmxyz/reth/blob/1ec4d462a22574ddf3baa88e507d6fbbf879eb40/crates/rpc/rpc-api/src/debug.rs#L14C13-L14C13

And https://ethereum.github.io/execution-apis/api-documentation/

And #130

**Comment by Eikix** [comment]
It seems this can be closed? cc @greged93
