### ISSUE TITLE
Create the Eth JSON RPC Debug API

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#520]
```[tasklist]
### Tasks
- [ ] go into the crates/eth-rpc/api folder and rename all files that end with <name of the api>_api.rs into <name of the api>.rs
- [ ] then still inside crates/eth-rpc/api folder, create the debug.rs api file
- [ ] create the skeleton for the debug api trait (drawing inspiration from other api files: eth_api.rs alchemy_api.rs web3_api.rs etc.) inside crates/eth-rpc/api/debug.rs
- [ ] create the skeleton for the debug server inside crates/eth-rpc/servers folder by setting every endpoint as unimplemented error
- [ ] stop for a second and investigate if it makes sense for each individual API to have its own error handling / error enum, or if it's better to use EthApiError (in the case above, unimplemented error is only exposed by EthApiError)
- [ ] you're done
```
