### ISSUE TITLE
feat: debug_getRawTransaction endpoint

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#521]
```[tasklist]
### Tasks
- [ ] Investigate how reth does it: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L883 | https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-api/src/debug.rs#L25
- [ ] Helper: investigate EIP2718 format to gain knowledge on return format of the endpoint
- [ ] Go into crates/eth-rpc/servers/debug.rs and implement the raw_transaction endpoint:
- [ ] Get the transaction from the transaction_by_hash endpoint of the client
- [ ] Format the transaction as an array of EIP2718 binary-encoded tx as per the specification of the debug API
- [ ] Test the feature, you may use an existing mock file in crates/core/mock/fixtures for your tx. note the fixtures are always starknet requests. you'll need to expect that the starknet tx in the fixtures will formatted into an eth tx, and then properly encoded, so you may need to pre-compute the end result, then expect it.
- [ ] Check that it matches with Geth's and Reth's implementation's logic
```
