### ISSUE TITLE
feat: debug_getRawBlock endpoint

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#522]
```[tasklist]
### Tasks
- [ ] Investigate how Reth does it: https://github.com/paradigmxyz/reth/blob/1ec4d462a22574ddf3baa88e507d6fbbf879eb40/crates/rpc/rpc-api/src/debug.rs#L21C1-L21C1 | https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L866
- [ ] Bonus: investigate RLP and block encoding to gain knowledge on the return format of the endpoint
- [ ] Go into crates/eth-rpc/servers/debug.rs and implement the getRawBlock endpoint, note that it should be called raw_block like in geth, as Rust does not use `get` prefixes
- [ ] Get a specific block by its id, either by using self.kakarot_client.get_eth_block_from_starknet_block or using eth-rpc block_by_number or block_by_hash, check with Kakarot core team first which approach to take
- [ ] Then, encode the fetched block
- [ ] Return it
- [ ] Test the feature using the mock server: create a request and response file for this request in crates/core/src/mock/fixtures called debug_getRawBlock.json in both folders, ⚠️ careful: the file is a starknet block request
```

**Comment by TAdev0** [comment]
@Eikix  may i try to work on this one ?
