### ISSUE TITLE
feat: debug_getRawHeader endpoint

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#523]
```[tasklist]
### Tasks
- [ ] Investigate how Reth implements this endpoint: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L632
- [ ] Check with core team if there needs to be a slight refactor in crates/core/src/models in order to expose the block header in kakarot client methods or not
- [ ] If not, then implement the debug_getRawHeader endpoint by getting a starknet_block, reconstructing the header as well as possible
- [ ] Then encode (RLP) the header an return it as per Reth's implementation
- [ ] Test the feature using the mock kakarot client, note that mock kakarot uses fixtures files in crates/core/src/mock/fixtures
```

**Comment by tcoratger** [comment]
@Eikix I can take this

**Comment by Eikix** [comment]
Let's do it!
