### ISSUE TITLE
feat: debug_getRawReceipts endpoint

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#524]
```[tasklist]
### Tasks
- [ ] Investigate how reth implements the raw receipts endpoint: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L680 (don't reinvent the wheel)
- [ ] Reproduce (if it makes sense) the logic of `debug_getRawTransaction` (test strategy and implem) -> https://github.com/kkrt-labs/kakarot-rpc/pull/867 -> most of the logic is in `src/eth_rpc/servers/debug_rpc.rs`
- [ ] Since we use reth types, we should be able to map over received receipts and use `receipt.with_bloom().encode_enveloped()` like in https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L680
```
