### ISSUE TITLE
dev: investigate & refactor to simpler field accesses using starknet rs new API

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#529]
**Describe the enhancement request**

```[tasklist]
### Tasks
- [ ] This PR has been merged recently in `starknet-rs` https://github.com/xJonathanLEI/starknet-rs/commit/99730bc7dbcffeedfa163be2a74aee3234da2a77
- [ ] We presently match lots of different tx types / and match different cases (maybepending, etc.) in order to access underlying types.
- [ ] Replace by new functions where applicable 
``` 

We're using macros to get underlying types:
```rust
macro_rules! get_invoke_transaction_field {
    (($field_v0:ident, $field_v1:ident), $type:ty) => {
        pub fn $field_v1(&self) -> Result<$type, ConversionError<()>> {
            match &self.0 {
                Transaction::Invoke(tx) => match tx {
                    InvokeTransaction::V0(tx) => Ok(tx.$field_v0.clone().into()),
                    InvokeTransaction::V1(tx) => Ok(tx.$field_v1.clone().into()),
                },
                _ => Err(ConversionError::TransactionConversionError(
                    constants::error_messages::INVALID_TRANSACTION_TYPE.to_string(),
                )),
            }
        }
    };
}
```

Starknet-rs has introduced accessors:
```rust
impl Transaction {
    pub fn transaction_hash(&self) -> &FieldElement {
        match self {
            Transaction::Invoke(tx) => tx.transaction_hash(),
            Transaction::L1Handler(tx) => &tx.transaction_hash,
            Transaction::Declare(tx) => tx.transaction_hash(),
            Transaction::Deploy(tx) => &tx.transaction_hash,
            Transaction::DeployAccount(tx) => &tx.transaction_hash,
        }
    }
}
```

**Describe Preferred Solution**
