### ISSUE TITLE
dev: code smells

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#531]
**Describe the enhancement request**
List all the found code smells contained on the repository in order to fix them.

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/532
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/536
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/537
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/538
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/544
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/556
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/560
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/561
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/566
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/567
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/570
```

**Comment by Eikix** [comment]
Assigning @ftupas as well to help and give more manpower to this important epic
