### ISSUE TITLE
dev: verify integration with Madara

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#626]
**Describe the enhancement request**

```[tasklist]
### Tasks
- [x] Verify correct connection to a Madara instance
- [x] Deploy Kakarot on Madara
- [x] Deploy opcodes.sol on Kakarot
- [x] Launch forge script
```

**Comment by greged93** [comment]
Steps:
- modify the pallet.rs file of the runtime crate in Madara to set the following:
```
parameter_types! {
    pub const UnsignedPriority: u64 = 1 << 20;
    pub const TransactionLongevity: u64 = u64::MAX;
    pub const InvokeTxMaxNSteps: u32 = 4_000_000;
    pub const ValidateMaxNSteps: u32 = 4_000_000;
    pub const ProtocolVersion: u8 = 0;
    pub const ChainId: Felt252Wrapper = SN_GOERLI_CHAIN_ID;
    pub const MaxRecursionDepth: u32 = 1000;
}
```
- run Madara with `cargo run --release -- setup --chain=dev --from-remote && cargo run --release -- --dev`.
- deploy kakarot by going to the RPC repo and running `make build-kakarot && make deploy-kakarot`.
- Update your .env file with the correct value for DEPLOYER_ACCOUNT_ADDRESS, DEPLOYER_ACCOUNT_PRIVATE_KEY,
KAKAROT_ADDRESS, PROXY_ACCOUNT_CLASS_HASH, EXTERNALLY_OWNED_ACCOUNT_CLASS_HASH, CONTRACT_ACCOUNT_CLASS_HASH.
- run the rpc with `make run`
- run `cd lib/kakarot && PRIVATE_KEY=... forge script solidity_contracts/scripts/PlainOpcodes.s.sol --broadcast --legacy --rpc-url http://0.0.0.0:3030". The PRIVATE_KEY should be the same as set in the .env file of kakarot-rpc under EVM_PRIVATE_KEY.
