### ISSUE TITLE
dev: remove usage of Feeder Gateway in estimateGas and simulateTransaction, replace by RPC

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#649]
**Describe the enhancement request**

Since Madara and Pathfinder implement simulateTx route, stop using the SequencerGateway for testing, simulating a tx, and estimating gas.

```[tasklist]
### Tasks
- [ ] Implement the estimateGas and simulateTransaction using the RPC Provider
- [ ] Delete all mentions of the SequencerGateway (in config and other crates)
- [ ] Test using Katana (test sequencer)
- [ ] Remove Network subtlety, the Kakarot Client no longer needs to be aware of its network
```

**Comment by Eikix** [comment]
Waiting for Madara to implement simulateTransaction
