### ISSUE TITLE
feat: create an end-to-end test in eth-rpc>tests>integration.rs 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#651]
# Feature Request

**Describe the Feature Request**

We need more integration test in eth-rpc crate.

```[tasklist]
### Tasks
- [ ] Create a test case that uses Katana as fixture
- [ ] Deploy an erc20 smart contract
- [ ] Call balance of EOA
- [ ] Invoke transferFrom to another address, e.g. 0xabde1
- [ ] Call balance of 0xabde1
- [ ] Call transaction receipt on the transaction
- [ ] Call getLogs to check Transfer event
```
