### ISSUE TITLE
feat: track and update RPC to adopt for both kakarot0 and kakarot-ssj the new EOA tx parameter format (encoded tx + tx_info.signature)

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#663]
### Describe the Feature Request

Soon the new EOA API will be merged in KKT0 and both codebases will adopt the same expected encoded transaction format for `__validate__` and `__execute__`

https://github.com/kkrt-labs/kakarot/issues/829

Track this issue and update the RPC accordingly:
```[tasklist]
### Tasks
- [ ] In eth_sendRawTransaction, in KakarotClient.send_transaction, decode transaction
- [ ] Extract Signature and put it in Starknet Transaction signature field as per the EOA expects: 5 fields, r.low, r.high, s.low, s.high, v
- [ ] Re-encode the tx without the signature, [in the correct order ](https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/contracts/src/eoa.cairo) check: https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/utils/src/eth_transaction.cairo
- [ ] Send the tx
```
