### ISSUE TITLE
feat: investigate hive revival 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#670]
# Feature Request

**Describe the Feature Request**

```[tasklist]
### Tasks
- [ ] Look at existing hive utils codebase. Look at how codegen of Madara pre-state is done. Is it clean? Note: we know we want to use Madara for Hive test suite.
- [ ] If the utils are not good, sync on what to do: clean-up? or re-think strategy to load a Hive pre-state.
- [ ] Try to run Hive in the current state of RPC and Madara
``` 

**Describe Preferred Solution**
