### ISSUE TITLE
feat: investigate Log Blooms (currently unimplemented) in the RPC

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#671]
# Feature Request

**Describe the Feature Request**

Currently, we don't handle log blooms in the RPC.

Starknet uses event keys internally. 

```[tasklist]
### Tasks
- [x] Investigate how other RPC clients handle log blooms
- [x] Investigate how in practice log blooms are queried in Eth RPC clients
- [x] Investigate how to adapt log blooms to Starknet
```

**Comment by Eikix** [comment]
Result of the timebox:
- We can use Reth's library to iterate over logs and populate the log bloom filter field in the block

See later for caching

Warning: the operation seems slow
