### ISSUE TITLE
dev: investigate building blocks on substrate (assembling Moonbeam, Madara,...)

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#672]
**Describe the enhancement request**
Investigate the possibility of building a substrate sequencer using the pallet from Madara for the execution and the RPC layer from Moonbeam. 

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/680
- [ ] Build a basic sequencer from the substrate example
- [ ] Use the Madara starknet pallet crate in order to have this as the execution layer
- [ ] Use the Moonbeam RPC crate (?) to accept incoming transaction and place them in the mempool.
- [ ] Add adaptors to convert Eth transactions into a Starknet transaction and execute it.
```
