### ISSUE TITLE
refactor: fetch dynamically the chain_id of the underlying network instead of using a constant

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#673]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] Make sure that https://github.com/kkrt-labs/kakarot-ssj/issues/641 is adopted
- [ ] Same for KKT0: https://github.com/kkrt-labs/kakarot/issues/848
- [ ] Replace all occurences of chain_id constants by chain_id calls to starknet provider
- [ ] Test
- [ ] Replace in signature injection this pattern
```

**Comment by TAdev0** [comment]
@Eikix  may i work on this issue?  I did the first requirement on kakarot ssj, and it seems it also implemented in kkt 0?

**Comment by greged93** [comment]
Can we close this @Eikix ?
