### ISSUE TITLE
dev: improve the testing

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#684]
**Describe the enhancement request**

```[tasklist]
### Tasks
- [ ] Implement a macro in order to remove a lot of the redundant code (setup, loading and assertions are similar in a lot of cases).
- [ ] Use `mockall` crate in order to mock the starknet_client or the provider.
- [ ] Move tests that are currently in the integration tests folder and are considered unit tests back to their respective file.
- [ ] If needed, move the test_utils file out of the integration tests and place them behind a feature flag as to be able to import them in the integration tests.
```

**Comment by greged93** [comment]
After review of the current testing, it was decided to keep it has is in order to avoid mixing different testing methods
