### ISSUE TITLE
dev: clean up and productionize benchmark folder

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#694]
**Describe the enhancement request**

currently, we can benchmark TPS on Madara / Katana by tweaking slightly the benchmarking node project.
we need to make it more streamlined, easy to use, and more importantly reliable.

the hard part of this load testing is to understand what is TPS in the sense of a sequencer: @bajpai244 proposed a heuristic which is the speed at which the mempool/fifo queue is unstacked.
that yields the following scenario: 
- start the sequencer
- start firing txs, do not record metrics of TPS
- after 30s, start measuring TPS
- after 60s, stop the experiment.
this places the sequencer into a state of load, and only starts the measurement after it has been running for a while.

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [x] read artillery docs to understand the framework
- [x] switch from node to bun and switch to typescript
- [x] audit / reduce the amount of code used
- [x] create different scenarios: ether transfers, erc20 transfers, etc.
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/698
```
