### ISSUE TITLE
dev: investigate websocket capabilities for Kakarot RPC

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#706]
```[tasklist]
### Tasks
- [x] investigate if jsonrpsee can support web sockets
- [x] investigate which evm routes are needed for block scout
- [ ] investigate the most used evm routes for ws by devs
- [ ] classify them by priority level
- [ ] propose first implementation of ws on kakarot rpc
```

**Comment by Eikix** [comment]
Noticing reth's implementation:
https://github.com/paradigmxyz/reth/blob/6430731fff06bfde15318667240d5738505fd6f8/crates/rpc/rpc/src/eth/pubsub.rs#L28

**Comment by hhamud** [comment]
can I be assigned to this one? @greged93 @tcoratger

**Comment by Eikix** [comment]
we had one request for WS by a PERP dex, but this can wait, let's close for now
