### ISSUE TITLE
feat: investigate execution trace route

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#707]
```[tasklist]
### Tasks
- [ ] Investigate the relevance of building a execution trace route in the context of kakarot
- [ ] Read how Geth's execution trace API works
- [ ] Read how Reth's execution trace API works
- [ ] See who uses execution trace API and if it's useful for us (maybe it's used by MEV bots, but we are starting without fee market, etc.)
- [ ] Ask on Reth / Geth telegram channels who uses execution trace API
```

**Comment by Eikix** [comment]
@bajpai244 provided a source for help:

https://www.youtube.com/watch?v=b8RdmGsilfU&t=804s

**Comment by Eikix** [comment]
I think this can be closed cc @greged93
