### ISSUE TITLE
epic: migrate the RPC to use mongo db

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#728]
# Feature Request
The RPC is currently using a http (gateway) or rpc (provider) service in order to serve requests. This needs to be migrated to the use of a database.

```[tasklist]
### Tasks
- [x] Migrate all the rpc routes to use a mongo db.
- [ ] Use mockall crate for the mocking of the database.
- [ ] Use a docker compose for integration testing.
```
