### ISSUE TITLE
epic: bump dependencies 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#731]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/732
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/733
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/734
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/735
```
