### ISSUE TITLE
devops: audit Kakarot RPC dockerfile  

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#763]
context: 
we're moving slowly but surely to production readiness
our dockerfiles are used for integration testing and even running local nodes of Kakarot

```[tasklist]
### Tasks
- [ ] audit the Kakarot RPC dockerfile
- [ ] optimize build time if possible
- [ ] optimize security
- [ ] optimize image size
``` 

KPIs:
- is build time faster?
- is image size smaller? by how much?
- are tools more consistent? safer?

**Comment by Rupeshprajapati2123** [comment]
Hey @Eikix is this issue still open? , Can I try optimizing the docker file

**Comment by greged93** [comment]
Find this misses scoping, what do you think @Eikix

**Comment by Eikix** [comment]
It'd be nice to do some continuous improvement on our docker files tbh, not sure how but def an Onlydust bounty to bring docker build times lower / image size lower would be welcome

We can:
1/ close this issue
2/ create a continuous improvement (Kaizen) EPIC to optimize docker and tag it as good first issue + odhack or onlydust bounties
3/ create 2 sub issues for the epic:
a/ make docker builds provably faster
b/ make docker images provably smaller

**Comment by greged93** [comment]
I'm not sure this fits as good first issue if the scoping is just "make faster", are you sure you want to make these?

**Comment by Eikix** [comment]
> I'm not sure this fits as good first issue if the scoping is just "make faster", are you sure you want to make these?
> 
> > b/ make docker images provably smaller
> 
> What do you mean here?

In the Kakarot main repo, someone worked on making the image size of kakarot smaller, from almost 10gb to 5gb or smth, i dont recall well
I thought this could work here too

**Comment by greged93** [comment]
ok sounds good will make the epic!
