### ISSUE TITLE
feat: upgrade Starknet tx type to v3 and pay fees in STRK

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#773]
# Feature Request

**Describe the Feature Request**

To simplify our testnet fee strategy, we'll use the v3 tx type and pay fees in STRK.
At the SW appchain level, the STRK fees will be set to 0.

```[tasklist]
### Tasks
- [ ] make sure starknet rs is bumped to 0.9
- [ ] make sure katana can handle v3 txs and that the --disable-fee flag of katana sets both STRK and ETH fees to 0
- [ ] change transaction type in add raw transaction route to be v3 and pay in STRK
- [ ] set MAX_FEE in the tx v3 field to 0
```

**Comment by Eikix** [comment]
This task is still relevant, though not prio before Q1 2025. Just needs to be properly scoped.
