### ISSUE TITLE
epic: debug hive tests

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#782]
in hive fork repo of kakarot,
in simulators > ethereum > rpc > main.go, there re the tests:

```go

var tests = []testSpec{
	// HTTP RPC tests.
	// {Name: "http/BalanceAndNonceAt", Run: balanceAndNonceAtTest},               // ok
	// {Name: "http/CanonicalChain", Run: canonicalChainTest},                     // nok
	// {Name: "http/CodeAt", Run: CodeAtTest},                                     // ok
	// {Name: "http/ContractDeployment", Run: deployContractTest},                 // nok
	// {Name: "http/ContractDeploymentOutOfGas", Run: deployContractOutOfGasTest}, // nok
	// {Name: "http/EstimateGas", Run: estimateGasTest},                           // nok
	// {Name: "http/GenesisBlockByHash", Run: genesisBlockByHashTest},             // nok
	// {Name: "http/GenesisBlockByNumber", Run: genesisBlockByNumberTest},         // nok
	// {Name: "http/GenesisHeaderByHash", Run: genesisHeaderByHashTest},           // nok
	// {Name: "http/GenesisHeaderByNumber", Run: genesisHeaderByNumberTest},       // nok
	// {Name: "http/Receipt", Run: receiptTest},                                   // nok
	// {Name: "http/SyncProgress", Run: syncProgressTest},                         // nok
	{Name: "http/TransactionCount", Run: transactionCountTest},                 // nok
	// {Name: "http/TransactionInBlock", Run: transactionInBlockTest},             // nok
	// {Name: "http/TransactionReceipt", Run: TransactionReceiptTest},             // ok

	// HTTP ABI tests.
	// {Name: "http/ABICall", Run: callContractTest},         // ok
	// {Name: "http/ABITransact", Run: transactContractTest}, // nok
	// Disable WS tests as it's not yet implemented for Kakarot RPC
	// // WebSocket RPC tests.
	// {Name: "ws/BalanceAndNonceAt", Run: balanceAndNonceAtTest},
	// {Name: "ws/CanonicalChain", Run: canonicalChainTest},
	// {Name: "ws/CodeAt", Run: CodeAtTest},
	// {Name: "ws/ContractDeployment", Run: deployContractTest},
	// {Name: "ws/ContractDeploymentOutOfGas", Run: deployContractOutOfGasTest},
	// {Name: "ws/EstimateGas", Run: estimateGasTest},
	// {Name: "ws/GenesisBlockByHash", Run: genesisBlockByHashTest},
	// {Name: "ws/GenesisBlockByNumber", Run: genesisBlockByNumberTest},
	// {Name: "ws/GenesisHeaderByHash", Run: genesisHeaderByHashTest},
	// {Name: "ws/GenesisHeaderByNumber", Run: genesisHeaderByNumberTest},
	// {Name: "ws/Receipt", Run: receiptTest},
	// {Name: "ws/SyncProgress", Run: syncProgressTest},
	// {Name: "ws/TransactionCount", Run: transactionCountTest},
	// {Name: "ws/TransactionInBlock", Run: transactionInBlockTest},
	// {Name: "ws/TransactionReceipt", Run: TransactionReceiptTest},

	// // WebSocket subscription tests.
	// {Name: "ws/NewHeadSubscription", Run: newHeadSubscriptionTest},
	// {Name: "ws/LogSubscription", Run: logSubscriptionTest},
	// {Name: "ws/TransactionInBlockSubscription", Run: transactionInBlockSubscriptionTest},

	// // WebSocket ABI tests.
	// {Name: "ws/ABICall", Run: callContractTest},
	// {Name: "ws/ABITransact", Run: transactContractTest},
}
```

```[tasklist]
### Tasks
- [x] debug {Name: "http/CanonicalChain", Run: canonicalChainTest}
- [x] debug {Name: "http/ContractDeployment", Run: deployContractTest}
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/786
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/788
- [x] debug {Name: "http/GenesisBlockByHash", Run: genesisBlockByHashTest}
- [x] debug {Name: "http/GenesisBlockByNumber", Run: genesisBlockByNumberTest}
- [x] debug {Name: "http/GenesisHeaderByHash", Run: genesisHeaderByHashTest}
- [x] debug {Name: "http/GenesisHeaderByNumber", Run: genesisHeaderByNumberTest}
- [x] debug {Name: "http/Receipt", Run: receiptTest}
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/793
- [x] debug {Name: "http/TransactionCount", Run: transactionCountTest}
- [x] debug {Name: "http/TransactionInBlock", Run: transactionInBlockTest}
- [x] debug {Name: "http/TransactionReceipt", Run: TransactionReceiptTest}
- [x] debug {Name: "http/ABICall", Run: callContractTest}
- [x] debug {Name: "http/ABITransact", Run: transactContractTest}
```

**Comment by Eikix** [comment]
We just need to now debug running all the tests at the same time @greged93 
I get inconsistent results when trying to run the tests all together, sometimes 10 fail, sometimes 7, it's weird

Lmk if you can run all the tests at once
As far as I understand they all pass when ran alone

**Comment by greged93** [comment]
This can be closed with #880
