### ISSUE TITLE
dev: improve docker compose

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#812]
```[tasklist]
### Tasks
- [ ] refactor indexer service to not git clone inline
- [ ] add public config for docker compose 
- [ ] respect good practices in docker compose
```

**Comment by d-roak** [comment]
!

**Comment by d-roak** [comment]
i'm going to remove my assignment here. Sry Elias 님 😢

**Comment by greged93** [comment]
@Eikix can we close this?

**Comment by Eikix** [comment]
We can close it;
We can also open a new PR to make all the existing docker compose up to date if not the case now

**Comment by greged93** [comment]
Normally I updated the dockers during the release process but will give them a check again
