### ISSUE TITLE
feat: support latest release of Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#827]
# Feature Request

**Describe the Feature Request**

support release 0.3.1

```[tasklist]
### Tasks
- [x] note that now, coinbase, basefee, prevrandao, block_gas_limit is a storage var in kakarot.
- [x] these storage vars have getters
- [x] update basefee if applicable
- [x] update feehistory if applicable
- [x] update coinbase if applicable
- [x] update katana genesis / hive genesis binaries if applicable
```
