### ISSUE TITLE
feat: prepare for testnet true gas 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#856]
```[tasklist]
### Tasks
- [ ] disable SN fees on kakarot sepolia
- [ ] RPC sets max fee to 0
- [ ] basefee on kakarot > 0 
- [ ] fix call_helper estimate fee to take kakarot basefee and not 0
```

**Comment by greged93** [comment]
closed as all points have been completed
