### ISSUE TITLE
dev: store key value mapping of ETH TX HASH and SN TX HASH during send_raw_transaction

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#862]
**Describe the enhancement request**

current problem on sepolia testnet: some txs are being rejected by the sequencer, we lack the ability to log the SW sequencer
juno has no tracing/logs
we return only the ETH tx hash -> the SN tx hash is "lost" -> we cannot query the feeder gateway with the SN tx hash to understand wtf is happening

```[tasklist]
### Tasks
- [ ] When firing a tx (eth_send_raw_tx) -> store in mongodb eth tx hash <-> sn tx hash kv
- [ ] If insert fails, do not block send raw tx, fire log / and add TODO to fire alerting app
- [ ] In any case print both
```

**Comment by greged93** [comment]
this can be done if necessary with Grafana so closing for now
