### ISSUE TITLE
feat: implement `debug_getRawTransactions`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#890]
```[tasklist]
### Tasks
- [ ] Investigate how Reth implements this endpoint: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/debug.rs#L674
- [ ] Implement the debug_getRawTransactions endpoint by getting a list of transactions for the given block id.
- [ ] Then encode (RLP) the list and return it as per Reth's implementation
- [ ] Test the feature using the mock kakarot client, note that mock kakarot uses fixtures files in crates/core/src/mock/fixtures
```
