### ISSUE TITLE
Set up staging environment for test

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#893]
```[tasklist]
### Tasks
- [x] create docker compose
- [x] clean makefile
- [ ] check it works
- [ ] fix chain id problem on SN Sepolia
```
