### ISSUE TITLE
bug: getTransactionByHash is too slow to return Some(_) after tx is received by node

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#914]
# Bug Report

**Kakarot RPC version:**

Kakarot: v0.4

**Current behavior:**

Issue reported by Sweta on Telegram, triaged by QA testnet team.

Lifetime of a tx in EVM rpc layer:
user sends tx -> node validates tx -> node adds tx to mempool -> node broadcasts tx -> node includes tx in next block

Node should be able to answer to `getTransactionByHash` query as a soon as it validated the tx.
In our rpc, node is able to answer to `getTransactionByHash` query after tx is included in a pending block.

This lag is inconsistent with hardhat tool: ignition

**Expected behavior:**

Lag between reception of `eth_sendRawTransaction` and ability to query `eth_getTransactionByHash` should be sub 1 second.

**Steps to reproduce:**

https://www.notion.so/Kakarot-Test-Feedback-704c867b0b724b688a2d290c4d307ec4

```[tasklist]
### Tasks
- [ ] This bug issue is created on a hunch, verify the suspected cause of the bug in practice. Verify why Hardhat ignition thinks deploy tx is dropped when it is successful in practice
- [ ] Recommend a fix: e.g. write tx in DB when tx is received and valid, or something else.
- [ ] note that issue is not well-scoped, it is a so-called timebox -> investigative work concluded by a recommendation
```
