### ISSUE TITLE
feat: indexer should index reverted transactions related to Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#956]
# Feature Request

we need to solve txs that have cairovm crashes -> they are reverted but never indexed!

**Describe the Feature Request**

```[tasklist]
### Tasks
- [ ] Index reverted transactions that are related with Kakarot
- [ ] Success field is by design 0
- [ ] The only missing field is gas used for now, create another issue to track how to solve this
```

**Comment by Eikix** [comment]
Issue somewhat stale, though it's still unclear how to move forward with it, Fran mentioned that it's not so easy

**Comment by Eikix** [comment]
I think we already tackled this @greged93, wdyt

**Comment by greged93** [comment]
I think we handle out of resources tx but not eth validation failed transaction. To be fair we shouldn't have eth validation failed anymore in the execution layer because this should be caught in the pool.

**Comment by Eikix** [comment]
> I think we handle out of resources tx but not eth validation failed transaction. To be fair we shouldn't have eth validation failed anymore in the execution layer because this should be caught in the pool.

cc'ing @enitrat but I'm almost certain we also handle eth validation failed txs

**Comment by enitrat** [comment]
txs whose validation fail should indeed be dropped at the mempool level

**Comment by greged93** [comment]
@Eikix I'm not saying we should remove the checks at the execution level, just saying this as been added at the mempool level as well so "should" never reach execution.

**Comment by Eikix** [comment]
> @Eikix I'm not saying we should remove the checks at the execution level, just saying this as been added at the mempool level as well so "should" never reach execution.

There are edge cases of race conditions:
- tx 1 and tx 2 are in the mempool
- tx 1 and tx 2 are fired to be executed, tx 1 empties the balance of the acct, tx 2 will be `invalid` but this will only be caught in the cairo checks

what should be the behaviour wrt UX / user feedback?
for us, the tx will revert, the relayer will pay revert fees, but from the user standpoint this is an invalid tx -> it would've been dropped on L1
but what happens here? is the tx stuck in the pending mempool? i remember back in our previous updates, there was a weird situation where the tx hash was findable with eth_getTransactionByHash but not with eth_getTransactionReceipt, which stuck most SDKs

**Comment by greged93** [comment]
this shouldn't happen, if tx1 and tx2 make a transfer from the same account, tx2 will not be sent until the account's nonce has been increased to the correct value, meaning the balance of the account has been modified. If the balance is insufficient, tx2 will not be sent and stay in the "pending" state of the mempool until the account has sufficient balance for execution.

Will need to check all this in prod but normally using the mempool takes us a step closer to being "like" a node, meaning the ux should be better.

**Comment by Eikix** [comment]
I didn't follow what is the status of this?

As I understand we currently index in the RPC:
1. Out of cairo steps tx

We will soon index:
2. EVM revert when cairo precompile happened in the same tx

Remaining questions: Do we want to index transactions where EVM validation failed in the execute_from_outside endpoint (i.e. are Starknet reverted)?

**Comment by greged93** [comment]
I think this is superseaded by this [issue](https://github.com/kkrt-labs/kakarot-rpc/issues/1458)
