### ISSUE TITLE
bug: identify calldata limit in RPC and error out of `eth_sendRawTransaction` / `eth_call` synchronously

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#976]
# Bug Report

**Current behavior:**

Currently, if a transaction send more than ~23kb, i.e. 24k felts to the underlying SN system, the tx will be rejected at the Starknet level, asynchronously. It will therefore be irretrievably lost to the UX and wallet.

Since we manipulate 1 byte 1 felt in the RPC, we can add an environment variable "max calldata felts per tx" and error out of a call / tx synchronously if we know it will error for sure in the gateway.

```[tasklist]
### Tasks
- [ ] Add an env variable in the RPC: `MAX_FELTS_IN_CALLDATA`
- [ ] Compute the length of the calldata payload right before sending the SN tx to the SN node, if > `MAX_FELTS_IN_CALLDATA`, then error out
- [ ] When updating this number with SW, update it in prod
```
